### ISSUE TITLE
Nz domains are not parsing correctly

### ISSUE THREAD

**Issue by developernaren** [jwage/purl#72]
I am using version `0.0.7` and tested this upto `0.0.9`

```
$url = \Purl\Url::parse('https://naren.nz/');
echo $url->registerableDomain;
//produces null
//expected naren.nz
```

```
$url = \Purl\Url::parse('https://www.naren.nz/');
echo $url->registerableDomain;
//produces "www.naren.nz"
//expected naren.nz
```
Please let me know if you need additional information.

**Comment by jwage** [comment]
Thanks. Would you be willing to provide a failing test and a fix?

**Comment by jeremykendall** [comment]
Please make sure you’re using the most recent version the the public suffix list. Can’t look now but update instructions should be in README.

**Comment by jeremykendall** [comment]
Here you go: https://github.com/jwage/purl/blob/master/README.markdown#staying-up-to-date

**Comment by developernaren** [comment]
@jwage @jeremykendall It seems like the prefixes with  key `*` on their array are failing
```
'bd' => 
  array (
    '*' => 
    array (
    ),
  )
```
or 
```
 'nz' =>
  array (
    '*' =>
    array (
    ),
    'co' =>
    array (
      'blogspot' =>
      array (
      ),
    ),
  ),
```
There are few other like bd, pg etc.
This is fixed if you replace the content of the file

`vendor/jwage/purl/data/public-suffix-list.php`

with

`vendor/jeremykendall/php-domain-parser/data/public-suffix-list.php`

And also this code in `vendor/jeremykendall/php-domain-parser/library/Pdp/Parser.php`

```
if (array_key_exists('*', $publicSuffixList)) {
                array_unshift($publicSuffix, $part);
                $publicSuffixList = $publicSuffixList['*'];
                continue;
            }
```
adds all the parts in the domains to public suffix if there exist a key `*` for a given suffix.

So I guess the issue is as @jeremykendall  pointed out, the list is not updated and also I am not sure that the fix to this would be, updating the public prefix list or not letting everything with `*` key into the suffix list. And since the codes are in two different repos I am a bit confused.

Please let me know if I can be of help further.

**Comment by jeremykendall** [comment]
Updating the file using the CLI tool did not resolve your issue?

**Comment by developernaren** [comment]
No it did not.

**Comment by nyamsprod** [comment]
Seems that Purl uses v3 and not v5

**Comment by jeremykendall** [comment]
That’s due to some php extension requirements in newer versions of php-domain-parser that are not required by purl. If @jwage is OK with that I think it’s safe to upgrade.

**Comment by nyamsprod** [comment]
Beside the intl extension I don't believe there are any other dependencies that I'm aware of

**Comment by nyamsprod** [comment]
Using v5 it does work ...

```php
use Pdp\Cache;
use Pdp\CurlHttpClient;
use Pdp\Manager;

require 'vendor/autoload.php';

$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();
$domain = $rules->resolve('naren.nz');
echo '<pre>', json_encode($domain, JSON_PRETTY_PRINT);
```
And the result is 

```javascript
{
    "domain": "naren.nz",
    "registrableDomain": "naren.nz",
    "subDomain": null,
    "publicSuffix": "nz",
    "isKnown": true,
    "isICANN": true,
    "isPrivate": false
}
```

**Comment by jwage** [comment]
We can upgrade 👍
